script: bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: qVYTLF6Zov5UMp1G0bHtHNIBp6djN56R1cftKv+nxN02ZXqaa9J323i/tOrVSW5acsXK7L1pCcZAdnN/cK5taHGa6EPZXkGppDayCh7h4x6kxM8IqWgEzWGTt/PLkPPkcFbx8i06hNLJlXh7SlcojB3aUWB8WNg41zWRatpQ8C7P4j4R/T3GCq4vLlVI0wXOkLRoZmxhU8FXqZadsA2f7Zhz91zrsPZDbHQzPjlRZg0TNYX5ABUdf80t/fUqq4/4CF/6Ldvznu5iVwCDrpoQfwlt8j/XunfDyTy7FWYgcImURSohrXwNJmegf2D401HSAdJwkvrb2QJbwTWChhIBSbqJ+1Ucsw8+WBbENsRIzimg/J/6iBftOOap3f9GWAUf2Pflhw0ijZCP1dcm59MzPLbLWFz31zanu7VTwXfd1Fm+jopFKOm+WuT2aHxkwX2JA0db5Ql8AI8f37p/8yWjd7Vx1HLzuTxsoj+29mC4Vbq+L7mMAZ89VWR8xWtvNbxwkqb9GrfmEkOE9msBtJCuY+FkirZgPNnE8NUbfbV5wyczr4VeDJHtm0rivfYhE5FGsMMQ1weetfBAIbLF4NxDUPu0ZMtdpSPR3GH991HKPWSvxYqydv4FW7nxiF+/ofhWGKxYpkYTnQ4a+SYw85nX1YwnZV5prnm9hLdsbkJHMHE=
  app: still-spire-48025
